import 'package:flutter/foundation.dart';
import 'package:novawallet/fake_backend/remote_operation_result.dart';
import 'package:novawallet/sync/domain/operation_payload.dart';

/// Immutable record stored in the remote idempotency ledger.
///
/// Records the original user intent payload, the resulting [RemoteOperationResult],
/// and the settlement metadata.
@immutable
class RemoteIdempotencyRecord {
  /// Stable idempotency key generated by the client.
  final String idempotencyKey;

  /// Logical operation ID.
  final String operationId;

  /// Operation type (e.g. 'send', 'contribution').
  final String operationType;

  /// The original payload map submitted with the operation.
  final Map<String, dynamic> payload;

  /// The outcome returned to the client.
  final RemoteOperationResult result;

  /// Timestamp when this record was written to the ledger.
  final DateTime recordedAt;

  const RemoteIdempotencyRecord({
    required this.idempotencyKey,
    required this.operationId,
    required this.operationType,
    required this.payload,
    required this.result,
    required this.recordedAt,
  });

  /// Validates whether an incoming [OperationPayload] matches the recorded payload.
  ///
  /// Used to detect conflicting idempotency key reuse per requirement SYNC-009.
  bool matchesPayload(OperationPayload incomingPayload) {
    if (incomingPayload.type.name != operationType) {
      return false;
    }

    final incomingMap = incomingPayload.toMap();

    // Check amount
    if (incomingMap['amountKobo'] != payload['amountKobo']) {
      return false;
    }

    // Type-specific field checks
    if (operationType == 'send') {
      if (incomingMap['recipientAccountNumber'] !=
          payload['recipientAccountNumber']) {
        return false;
      }
      if (incomingMap['recipientName'] != payload['recipientName']) {
        return false;
      }
      if (incomingMap['bankName'] != payload['bankName']) {
        return false;
      }
      if (incomingMap['narration'] != payload['narration']) {
        return false;
      }
    } else if (operationType == 'contribution') {
      if (incomingMap['goalId'] != payload['goalId']) {
        return false;
      }
      if (incomingMap['goalName'] != payload['goalName']) {
        return false;
      }
    }

    return true;
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is RemoteIdempotencyRecord &&
          other.idempotencyKey == idempotencyKey &&
          other.operationId == operationId &&
          other.operationType == operationType &&
          mapEquals(other.payload, payload) &&
          other.result == result &&
          other.recordedAt.isAtSameMomentAs(recordedAt));

  @override
  int get hashCode => Object.hash(
    idempotencyKey,
    operationId,
    operationType,
    result,
    recordedAt.toUtc().millisecondsSinceEpoch,
  );

  @override
  String toString() =>
      'RemoteIdempotencyRecord(key: $idempotencyKey, opId: $operationId, '
      'type: $operationType, ref: ${result.remoteReference})';
}
